"""Dockerfile образов пакета интеграции (plan Р8, FR-027).

- ``package-sdk image observer --package . [--entrypoint m:f] [--base IMAGE]`` — образ
  вида ``observer`` от базового образа наблюдателя поставки, в котором уже стоят
  ``package-sdk[connector]`` и клиент ядра; сверху — код интеграции пакета. Единая точка
  входа ``python -m package_sdk.connector`` читает ревизию агента и сама находит
  наблюдателя по ``executor.params.entrypoint``. ``--entrypoint`` добавляет проверку
  при сборке: образ без этого наблюдателя не соберётся.
- ``package-sdk image skills --package . --modules a,b [--base IMAGE]`` — хост
  скиллов: образ раннера поставки в режиме ``skills`` с интеграцией пакета и списком
  модулей скиллов в ``CONTROL_PLANE_SKILLS_LOCAL_PACKAGES``.

Безопасность сборки:

- компоненты платформы (SDK, клиент ядра) берутся только из базового образа: из
  публичного индекса пакетов их не ставят — там таких имён нет, и чужой пакет с тем же
  именем подменил бы их (dependency confusion). Сборка проверяет, что базовый образ их
  содержит, и падает, если нет;
- базовый образ по умолчанию не задан: ``--base`` или ``--build-arg``;
- в образ копируются только ``pyproject.toml``, ``README.md`` и ``src/`` интеграции,
  а ``.dockerignore`` рядом пропускает в контекст сборки только их: ``.env``, ``.git``
  и ``.venv`` пакета в образ не попадают.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from package_sdk.model import PackageError, _rel, package_name

ENTRYPOINT = re.compile(r"^[A-Za-z_][\w.]*:[A-Za-z_]\w*$")
MODULE = re.compile(r"^[A-Za-z_][\w.]*(:[A-Za-z_]\w*)?$")
IMAGE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/:@-]{0,254}$")

OBSERVER = """\
# The observer image of the package {key} (executor kind observer). Generated by:
#   package-sdk image observer --package {package}{extra_args}
# Build from the package directory: docker build{build_arg} -f {dockerfile} .
# The base is the observer image of the platform: package-sdk[connector] and the core
# client are already there. They are never installed from the public index.
ARG BASE_IMAGE{base}
FROM ${{BASE_IMAGE}}
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1
RUN python -c "import package_sdk.connector, control_plane_client" \\
    || (echo "the base image has no package-sdk[connector] and core client" >&2; exit 1)
# The versions of the platform components are constraints of the install: an integration
# that needs another one fails the build instead of pulling it from the index.
RUN python -c "from importlib.metadata import version as v; \\
print('package-sdk==' + v('package-sdk')); \\
print('control-plane-client==' + v('control-plane-client'))" > /tmp/platform-constraints.txt
WORKDIR /srv
{copy}RUN pip install --no-cache-dir --constraint /tmp/platform-constraints.txt ./integration
{check}RUN useradd -u 10001 -m -s /usr/sbin/nologin connector \\
    && mkdir -p /data && chown connector:connector /data
# The replica volume is /data (CONNECTOR_DATA_DIR), the node's secrets are
# /run/secrets/<name>, the agent's PAT is /run/secrets/agent-pat: none of them is
# written into the environment of the image.
ENV CONNECTOR_DATA_DIR=/data HOME=/home/connector
USER connector
ENTRYPOINT ["python", "-m", "package_sdk.connector"]
"""

CHECK = """\
# The observer named by the agent must be in the image
RUN python -c "from package_sdk.connector import load_entrypoint; load_entrypoint('{entrypoint}')"
"""

SKILLS = """\
# The skills host of the package {key}: the runner image of the platform in the skills
# mode with the integration of the package. Generated by:
#   package-sdk image skills --package {package} --modules {modules}{extra_args}
# Build from the package directory: docker build{build_arg} -f {dockerfile} .
ARG RUNNER_IMAGE{base}
FROM ${{RUNNER_IMAGE}}
# The Python of the executor's environment in the runner image
ARG RUNNER_PYTHON=python
USER root
RUN "$RUNNER_PYTHON" -c "import skill_sdk, control_plane_client" \\
    || (echo "the runner image has no skill-sdk and core client" >&2; exit 1)
RUN "$RUNNER_PYTHON" -c "from importlib.metadata import version as v; \\
print('skill-sdk==' + v('skill-sdk')); \\
print('control-plane-client==' + v('control-plane-client'))" > /tmp/platform-constraints.txt
{copy}RUN uv pip install --python "$RUNNER_PYTHON" --constraint /tmp/platform-constraints.txt \\
    /opt/package/integration
ENV RUNNER_MODE=skills CONTROL_PLANE_SKILLS_LOCAL_PACKAGES="{modules}"
USER 10001
"""


def _source(package_dir: Path, source: str | None) -> str:
    """Каталог python-проекта интеграции относительно пакета («» — сам пакет)."""
    candidate = source or ("integration" if (package_dir / "integration").is_dir() else ".")
    if not (package_dir / candidate / "pyproject.toml").is_file():
        raise PackageError(
            f"{_rel(package_dir / candidate)}: no pyproject.toml — point to the integration code "
            "(--source) or create it: package-sdk init --integration"
        )
    if not (package_dir / candidate / "src").is_dir():
        raise PackageError(f"{_rel(package_dir / candidate)}: integration code is expected in src/")
    return "" if candidate in (".", "./") else candidate.strip("/") + "/"


def _copy(package_dir: Path | None, source: str, target: str) -> str:
    """COPY только проекта интеграции: pyproject.toml, README.md (если есть) и src/."""
    lines = [f"COPY {source}pyproject.toml {target}/pyproject.toml"]
    if package_dir is not None and (package_dir / source / "README.md").is_file():
        lines.append(f"COPY {source}README.md {target}/README.md")
    lines.append(f"COPY {source}src {target}/src")
    return "\n".join(lines) + "\n"


def dockerignore(package_dir: Path, *, source: str | None = None) -> str:
    """.dockerignore контекста сборки: только проект интеграции, без кэшей."""
    return render_dockerignore(_source(package_dir, source))


def render_dockerignore(prefix: str) -> str:
    lines = [
        "# Generated by package-sdk image: only the integration code goes into the build context.",
        "**",
        f"!{prefix}pyproject.toml",
        f"!{prefix}README.md",
        f"!{prefix}src/**",
        "**/__pycache__",
        "**/*.pyc",
    ]
    return "\n".join(lines) + "\n"


def _key(package_dir: Path) -> str:
    return package_name(package_dir)


def _base(base: str | None, arg: str) -> tuple[str, str, str]:
    if base is not None and not IMAGE.match(base):
        raise PackageError(f"--base {base!r}: not an image reference")
    if base:
        return f"={base}", f" --base {base}", ""
    return "", "", f" --build-arg {arg}=<image>"


def observer_dockerfile(
    package_dir: Path,
    *,
    entrypoint: str | None = None,
    source: str | None = None,
    base: str | None = None,
    dockerfile: str = "Dockerfile",
) -> str:
    return render_observer(
        _key(package_dir),
        _source(package_dir, source),
        package_dir=package_dir,
        entrypoint=entrypoint,
        base=base,
        dockerfile=dockerfile,
    )


def render_observer(
    key: str,
    prefix: str,
    *,
    package_dir: Path | None = None,
    entrypoint: str | None = None,
    base: str | None = None,
    dockerfile: str = "Dockerfile",
) -> str:
    """Dockerfile наблюдателя без обращения к файлам пакета (init пишет его до файлов)."""
    if entrypoint is not None and not ENTRYPOINT.match(entrypoint):
        raise PackageError(f"--entrypoint {entrypoint!r}: expected the form module:function")
    default, base_arg, build_arg = _base(base, "BASE_IMAGE")
    return OBSERVER.format(
        key=key,
        package=".",
        extra_args=(f" --entrypoint {entrypoint}" if entrypoint else "") + base_arg,
        build_arg=build_arg,
        base=default,
        dockerfile=dockerfile,
        copy=_copy(package_dir, prefix, "./integration"),
        check=CHECK.format(entrypoint=entrypoint) if entrypoint else "",
    )


def skills_dockerfile(
    package_dir: Path,
    *,
    modules: list[str],
    source: str | None = None,
    base: str | None = None,
    dockerfile: str = "Dockerfile.skills",
) -> str:
    if not modules:
        raise PackageError("--modules: at least one module or skill entrypoint")
    for module in modules:
        if not MODULE.match(module):
            raise PackageError(f"--modules {module!r}: module or module:function")
    prefix = _source(package_dir, source)
    default, base_arg, build_arg = _base(base, "RUNNER_IMAGE")
    return SKILLS.format(
        key=_key(package_dir),
        package=".",
        modules=",".join(modules),
        extra_args=base_arg,
        build_arg=build_arg,
        base=default,
        dockerfile=dockerfile,
        copy=_copy(package_dir, prefix, "/opt/package/integration"),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="package-sdk image",
        description="Dockerfile of a package integration image: observer or skill host",
    )
    sub = parser.add_subparsers(dest="kind", required=True)
    for kind in ("observer", "skills"):
        cmd = sub.add_parser(kind, help=f"Dockerfile of the {kind} image")
        cmd.add_argument("--package", type=Path, default=Path("."), help="package directory")
        cmd.add_argument(
            "--source",
            help="python project of the integration in the package (default integration/)",
        )
        cmd.add_argument(
            "--base",
            help="base image of the delivery (otherwise --build-arg at build time); "
            + ("observer" if kind == "observer" else "runner"),
        )
        cmd.add_argument(
            "--out",
            type=Path,
            help="where to write; .dockerignore is written alongside, in the package directory",
        )
        if kind == "observer":
            cmd.add_argument(
                "--entrypoint", help="observer module:function — checked at build time"
            )
        else:
            cmd.add_argument(
                "--modules", required=True, help="comma-separated modules or skill entrypoints"
            )
    args = parser.parse_args(argv)
    try:
        default = "Dockerfile" if args.kind == "observer" else "Dockerfile.skills"
        name = args.out.name if args.out else default
        if args.kind == "observer":
            text = observer_dockerfile(
                args.package,
                entrypoint=args.entrypoint,
                source=args.source,
                base=args.base,
                dockerfile=name,
            )
        else:
            modules = [m.strip() for m in args.modules.split(",") if m.strip()]
            text = skills_dockerfile(
                args.package, modules=modules, source=args.source, base=args.base, dockerfile=name
            )
        ignore = dockerignore(args.package, source=args.source)
    except PackageError as error:
        print("error:", error, file=sys.stderr)
        return 1
    if not args.out:
        print(text, end="")
        return 0
    args.out.write_text(text, encoding="utf-8")
    print("written", _rel(args.out))
    ignore_path = args.package / ".dockerignore"
    if not ignore_path.exists():
        ignore_path.write_text(ignore, encoding="utf-8")
        print("written", _rel(ignore_path))
    elif ignore_path.read_text(encoding="utf-8") != ignore:
        print(
            f"warning: {_rel(ignore_path)} already exists and differs from the required one — "
            "only the integration code must go into the build context (package-sdk image "
            "without --out shows the Dockerfile, the dockerignore — function "
            "package_sdk.image.dockerignore)",
            file=sys.stderr,
        )
    return 0
